// Mapa local de icono por medalla (Ionicons).
// Para añadir una medalla nueva:
//   1) insertar la fila en la tabla `badges` de Supabase (id, name, description, icon_key)
//   2) añadir aquí esa misma `id` -> nombre de icono de Ionicons
export const BADGE_ICON = {
  streak_3: 'flame-outline',
  streak_7: 'flame',
  streak_30: 'trophy-outline',
  first_post: 'rocket-outline',
  activities_5: 'flash-outline',
  activities_25: 'fitness-outline',
  distance_10: 'map-outline',
  variety_3: 'apps-outline',
  climb_start: 'trending-up-outline',
  planner_3: 'calendar-outline',
  week_3: 'calendar-number-outline',
  active_300: 'time-outline',
  first_route: 'navigate-outline',
  first_plan: 'calendar-outline',
  first_meetup: 'people-outline',
  activities_10: 'footsteps-outline',
  activities_50: 'barbell-outline',
  activities_100: 'medal-outline',
  activities_250: 'diamond-outline',
  streak_60: 'bonfire-outline',
  streak_100: 'infinite-outline',
  weeks_4: 'calendar-number-outline',
  distance_5: 'map-outline',
  distance_25: 'trail-sign-outline',
  distance_50: 'trail-sign-outline',
  distance_100: 'earth-outline',
  distance_250: 'globe-outline',
  distance_500: 'compass-outline',
  distance_1000: 'planet-outline',
  active_600: 'timer-outline',
  active_1500: 'hourglass-outline',
  active_3000: 'stopwatch-outline',
  active_6000: 'watch-outline',
  variety_5: 'grid-outline',
  variety_10: 'color-palette-outline',
  elevation_1000: 'trending-up-outline',
  elevation_5000: 'analytics-outline',
  elevation_10000: 'triangle-outline',
  climb_10: 'hand-left-outline',
  climb_25: 'podium-outline',
  climb_vertical_1000: 'trending-up',
  planner_10: 'calendar-clear-outline',
  planner_25: 'checkbox-outline',
  route_5: 'navigate-outline',
  route_25: 'map-outline',
  route_50: 'compass-outline',
  meetup_3: 'people-circle-outline',
  meetup_10: 'people-outline',
};

export function iconForBadge(badgeId) {
  return BADGE_ICON[badgeId] || 'ribbon-outline';
}
